after_script: ['wget https://scrutinizer-ci.com/ocular.phar', 'php ocular.phar code-coverage:upload
    --format=php-clover coverage.clover']
before_script: ['curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar
    xz -C /tmp', cd /tmp/beanstalkd-1.10/, make, ./beanstalkd &, cd $TRAVIS_BUILD_DIR ]
    - flags="--prefer-dist"
    - composer install $flags
    - bin/composer install $flags
install: [composer self-update --stable, 'composer global require "fxp/composer-asset-plugin:~1.1.1"',
  composer install]
language: php
php: [5.5]
script: [vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover]
